/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package InternalModel;

import java.util.Optional;

public class App {

    public static void main(String[] args) {
        Simulation s = new Simulation();

        System.out.println(s.arrayWireGrid);
        s.simulate(1);
        System.out.println(s.arrayWireGrid);
        s.simulate(1);
        System.out.println(s.arrayWireGrid);
        s.simulate(1);
        System.out.println(s.arrayWireGrid);
        s.simulate(1);
        System.out.println(s.arrayWireGrid);

        //TODO: unit tests with mockito for wireGrid
        //TODO: logic gates rotation - unit testy
        //TODO: Logic gate return (LOGIC_VALUE, position).
        //TODO: umieść LogicLEemnt w interface


    }
}