/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package InternalModel;

import java.util.Optional;

public class App {

    public static void main(String[] args) {
        Simulation s = new Simulation();

        System.out.println(s.arrayWireGrid);
        s.simulate(1);
        System.out.println(s.arrayWireGrid);
        s.simulate(1);
        System.out.println(s.arrayWireGrid);
        s.simulate(1);
        System.out.println(s.arrayWireGrid);
        s.simulate(1);
        System.out.println(s.arrayWireGrid);

        //TODO: Change upUnbound to Unbound
        //TODO: logic gates rotation
        //TODO: Logic gate return (LOGIC_VALUE, position).
        // użycie Optional ph.parent().map(h -> String.valueOf(h.pid())).orElse("N/A"));
        // change WIreGrid to abstract class with Unbound array


    }
}


//Iterator<T> for iterator
//Iterable for collections