/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package InternalModel;

public class App {

    public static void main(String[] args) {
        Simulation s = new Simulation();

        System.out.println(s.arrayWireGrid);
        s.runOnce();
        System.out.println(s.arrayWireGrid);
        s.runOnce();
        System.out.println(s.arrayWireGrid);
        s.runOnce();
        System.out.println(s.arrayWireGrid);
        s.runOnce();
        System.out.println(s.arrayWireGrid);
        //TODO: test Simulation
    }
}