/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package LogicCircuitSimulator;

import LogicCircuitSimulator.FxGUI.CircuitBoard.FXMLController.SimulationCanvasController;
import javafx.application.Application;
import javafx.fxml.FXMLLoader;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.stage.Stage;

import java.io.IOException;

public class App  extends Application {

    public static void main(String[] args) {
        launch(args);
    }
    public static Stage primaryStage;
    private static final String stageTitle = "Logic Circuit Simulator";

    @Override
    public void start(Stage stage) {
        primaryStage = stage;

        primaryStage.setTitle(stageTitle);

        FXMLLoader loader = new FXMLLoader();
        loader.setLocation(this.getClass().getResource("/FXML/StartMenu.fxml"));

        Parent pane = null;
        try {
            pane = loader.load();
        } catch (IOException e) {
            e.printStackTrace();
        }
        assert pane != null;
        Scene scene = new Scene(pane);
        primaryStage.setScene(scene);
        primaryStage.show();
        primaryStage.setResizable(false);

        // cleanup controller resources when window closes:
        //SimulationCanvasController controller = loader.getController();
        //primaryStage.setOnCloseRequest(e -> controller.shutdown());
    }
}